// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

const max = 4000000;

let a = 1;
let b = 2;
let sum = 0;

do {
if (b % 2 === 0) {
  sum += b;
}

c = a + b;
a = b;
b = c;
}
while (b <= max);

console.log(sum);