/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

const getFactors = (num) => {
  max = num;
  let numFactors = 0;
  for (let i = 1; i <= num; i++) {
    if (i > max) {
      break;
    }
    if (num % i === 0) {
      numFactors++;
      if (num / i !== i) {
        numFactors++;
        max = (num / i) - 1;
      };
    }
  }
  return numFactors;
}

let currentNum = 1;
let incrementBy = 2;

while (1) {
  let numFactors = getFactors(currentNum);
  if (numFactors > 100) console.log(numFactors);
  if (numFactors > 500) {
    break;
  }
  currentNum += incrementBy;
  incrementBy++;
}

console.log(currentNum);